------ADMIN-----
CREATE TABLE LMS_ADMIN(MANAGER_ID NUMBER PRIMARY KEY,MANAGER_NAME VARCHAR2(50),MANAGER_EMAIL VARCHAR2(70),MANAGER_PASSWORD VARCHAR2(40));
DESC LMS_ADMIN;
INSERT INTO  LMS_ADMIN VALUES(2921,'Pothiraj','Pothiraj@gmail.com','pothi@97');
---delete from lms_admin where manager_id=101;
SELECT * FROM LMS_ADMIN;

-----EMPLOYEE TABLE-----
CREATE TABLE LMS_EMPLOYEE(EMP_ID NUMBER GENERATED  ALWAYS AS IDENTITY START WITH 2930,EMP_NAME VARCHAR2(40), EMP_DEPARTMENT VARCHAR2(40),EMP_EMAIL VARCHAR2(50),EMP_PASSWORD VARCHAR2(50),
CONSTRAINT PK_EMP_ID  PRIMARY KEY(EMP_ID));
DESC LMS_EMPLOYEE;
SELECT * FROM LMS_EMPLOYEE;
COMMIT;




------leave request-------

CREATE TABLE LEAVE_RES(REQUEST_ID NUMBER  GENERATED  ALWAYS AS IDENTITY START WITH 100 ,EMP_ID NUMBER,REASON VARCHAR2(50),FROM_DATE DATE,TO_DATE DATE,
NO_OFDAYS NUMBER,STATUS VARCHAR2(40)DEFAULT 'PROCESSING',CONSTRAINT PK_REQUEST_ID  PRIMARY KEY(REQUEST_ID),
FOREIGN KEY( EMP_ID) REFERENCES LMS_EMPLOYEE(EMP_ID));
DESC LEAVE_RES;
SELECT*FROM LEAVE_RES;


commit;




-----leave status------

CREATE TABLE LEV_STATUS(MANAGER_ID NUMBER ,REQUEST_ID NUMBER,EMP_ID NUMBER ,STATUS VARCHAR2(30) DEFAULT 'PROCESSING',
FOREIGN KEY (REQUEST_ID)REFERENCES LEAVE_RES(REQUEST_ID));
DESC LEV_STATUS;

SELECT *FROM LEV_STATUS;


commit;

------leave balance------

CREATE TABLE LEAVE_BAL(EMP_ID NUMBER primary key,CAUSAL_LEV NUMBER DEFAULT 10,MEDICAL_LEV NUMBER DEFAULT 10,CAUSAL_LEV_BAL NUMBER DEFAULT 10,MEDI_LEV_BAL NUMBER DEFAULT 10,PAID_LEV NUMBER DEFAULT 0,
FOREIGN KEY (EMP_ID) REFERENCES LMS_EMPLOYEE (EMP_ID));
DESC LEAVE_BAL;
SELECT* FROM LEAVE_BAL;

commit;



